server:
  port: 8888 #the port where the config-server will be accessible
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/molorane/cloud-configs-gdp-2023.git
          cloneOnStart: true
  security:
    user:
      password: 1234 # the password which apps will use to access its configurations