server:
  port: 8888 #the port where the config-server will be accessible
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/workspace/GDP/micro-services/configfirst
          default-label: main
  security:
    user:
      password: 1234 # the password which apps will use to access its configurations