# Shared across all profiles
spring:
  application:
    name: lion #name of the application
  cloud:
    config:
      fail-fast: true #the service will not run if it can't reach the config-service
      password: 1234 #password of the config-service
      username: user #username of the config-service
      retry:
        initial-interval: 5000
        max-attempts: 1
---

resilience4j:
  circuitbreaker:
    instances:
      rhinoService:
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 5
        sliding-window-type: count_based
        wait-duration-in-open-state: 5s

# Local profile
spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: local