# Shared across all profiles
spring:
  application:
    name: rhino #name of the application
  cloud:
    config:
      fail-fast: true #the service will not run if it can't reach the config-service
      password: 1234 #password of the config-service
      username: user #username of the config-service
      retry:
        initial-interval: 5000
        max-attempts: 1
---

# Local profile
spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: local