server:
  port: 1964

service:
  vendor: Lion2

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        circuitbreakers:
            enabled: true
        ratelimiters:
            enabled: true

resilience4j:
  circuitbreaker:
    instances:
      rhinoService:
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 5
        sliding-window-type: count_based
        wait-duration-in-open-state: 5s